# Generated by Django 5.2.11 on 2026-02-27 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("venue", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=100)),
                ("date", models.DateTimeField()),
                ("description", models.TextField(blank=True)),
                ("ticket_url", models.URLField(blank=True)),
                ("is_upcoming", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="Mix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("audio_url", models.URLField(blank=True)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="mixes/"),
                ),
                ("genre", models.CharField(blank=True, max_length=100)),
                ("duration", models.DurationField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_featured", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Mix",
                "verbose_name_plural": "Mixes",
                "ordering": ["-created_at"],
            },
        ),
    ]
